# Copyright 2022, 2023, 2025 Contributors to the Nova-Vox project

# This file is part of Nova-Vox.
# Nova-Vox is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
# Nova-Vox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Nova-Vox. If not, see <https://www.gnu.org/licenses/>.


# this file contains constants that are used throughout Nova-Vox.
# Though it may look simple, please do not edit this file
# unless you are sure you know what you are doing.
# Changes can easily cause incompatibility with .nvx, .nvvb or other files,
# program instability or various other issues.

from C_Bridge import engineCfg

#data batching
sampleRate = 48000
tickRate = 250
batchSize = 192
tripleBatchSize = 576
halfTripleBatchSize = 288
LSTMBatchSize = 250000

#analysis spectral processing
filterBSMult = 4
DIOBias = 0.4
DIOBias2 = 0.2
DIOTolerance = 0.2
DIOLastWinTolerance = 0.9
filterTEEMult = 32
filterHRSSMult = 4
nHarmonics = 64
halfHarms = 33
ampContThreshold = 10
frameSize = nHarmonics + halfTripleBatchSize + 3
reducedFrameSize = halfHarms + halfTripleBatchSize + 1

#synthesis spectral processing
spectralRolloff1 = 144
spectralRolloff2 = 192
breCompPremul = 0.1
crfBorderAbs = 7
crfBorderRel = 0.1
maxVibratoSpeed = 0.15
maxVibratoStrength = 1.
vibratoEnvelopeExp = 0.25

#audio pipeline
audioBufferSize = 2048

#pitch curve synthesis
pitchTransitionLength = 25
pitchDipWidth = 40
pitchDipHeight = 0.2

#border synthesis
refPhonemeLength = 10
refTransitionLength = 4
refTransitionFrac = 0.2

#editor UI
octaves = 4

#self-identification
language = "en"
version = "1.0.1"

#devkit default values
defaultExpectedPitch = 0.
defaultSearchRange = 0.55
defaultVoicedThrh = 1.
defaultSpecWidth = 2
defaultSpecDepth = 30
defaultTempWidth = 2
defaultTempDepth = 10

#oto.ini parser
consonantEndOffset = 30

#control/reserved phoneme list
controlPhonemes = (
    ("-", "C"),
    ("=", "C"),
    (">", "C"),
    ("<", "C"),
    ("+", "R"),
    ("_0", "R"),
    ("_X", "R"),
    ("_autopause", "R")
)

#C bindings
config = engineCfg(sampleRate = sampleRate,
                   tickRate = tickRate,
                   batchSize = batchSize,
                   tripleBatchSize = tripleBatchSize,
                   halfTripleBatchSize = halfTripleBatchSize,
                   nHarmonics = nHarmonics,
                   halfHarmonics = int(nHarmonics / 2) + 1,
                   frameSize = frameSize,
                   breCompPremul = breCompPremul)
