name: Build Nova-Vox EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PyTorch CUDA 11.8
        run: pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 --index-url https://download.pytorch.org/whl/cu118

      - name: Install dependencies (ignore conflicts)
        run: pip install -r requirements.txt --no-deps

      - name: Install missing extras
        run: pip install numpy scipy librosa soundfile tqdm Pillow

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller Nova-Vox.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nova-Vox-EXE
          path: dist/
